# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM python:3.12-slim
ENV PYTHONUNBUFFERED=1
WORKDIR /app

# Copy project files
COPY pyproject.toml uv.lock README.md ./
COPY src ./src

# Install build tools and package
RUN pip install --upgrade pip setuptools build wheel \
    && pip install .

# Expose port for HTTP server
EXPOSE 8081

# Default command to start MCP over HTTP
CMD ["akshare-one-mcp", "--streamable-http", "--host", "0.0.0.0", "--port", "8081"]
